### ISSUE TITLE
Jest timeout error during project validation

### ISSUE THREAD

**Issue by jorgeruvalcaba** [kentcdodds/advanced-react-hooks#74]
Just downloaded this repo and ran `npm run setup --silent` but I'm getting this error in the project validation step:
```
FAIL  src/__tests__/03.extra-2.js (9.934 s)
  ● displays the pokemon

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      15 | })
      16 |
    > 17 | test('displays the pokemon', async () => {
         | ^
      18 |   render(<App />)
      19 |   const input = screen.getByLabelText(/pokemon/i)
      20 |   const submit = screen.getByText(/^submit$/i)

      at Object.<anonymous> (src/__tests__/03.extra-2.js:17:1)
```

Not sure if I should create the timeout mentioned there or if the Pokemon API is down. Were checking discord and previous issues, and seems uncommon.

**Comment by kentcdodds** [comment]
Yeah this is not common. We don't hit the actual API in tests so that shouldn't be it either. Something about your computer is causing the tests to take extra long and I'm not sure what it is I'm afraid 😬

**Comment by jorgeruvalcaba** [comment]
just commented this line and the test passed: `await screen.findByRole('heading', {name: /ditto/i})`

Not sure why tho 🤔

**Comment by kentcdodds** [comment]
I've figured this out! I had a bug in the testing setup. We mock backend requests (in development as well as in tests). In development we want the requests to be delayed to simulate a real environment. But in our tests we *don't* want that because then it'll take too long. So that explains why it's taking so long for you. I've fixed this in the react-workshop-app: https://github.com/kentcdodds/react-workshop-app/commit/c4b7b0bd7bdabe552e2b1bfcd390cf90dc749d56 and I've just pushed an update to this repo so you can try clone/setup over again and it should work without trouble.

Thanks for your patience.

**Comment by jorgeruvalcaba** [comment]
Thanks for your help @kentcdodds! It works fine now.
