### ISSUE TITLE
useDebugValue: inconsistency in format

### ISSUE THREAD

**Issue by vasilii-kovalev** [kentcdodds/advanced-react-hooks#82]
Marty the Money Bag 💰 says:
![image](https://user-images.githubusercontent.com/10310491/96583741-dda01a00-12e5-11eb-95a0-93f8b23aae91.png)

Should be in the end (according to the `after` image):
![image](https://user-images.githubusercontent.com/10310491/96583787-eb559f80-12e5-11eb-846a-0d29fef07e2b.png)

It seems it should be
``useMedia(\`${query}\`) => ${state}``

**Comment by vasilii-kovalev** [comment]
``\`${query}\` => ${state}`` is in the video as well, so maybe it is easier to change the `after` image only.

**Comment by kentcdodds** [comment]
Thanks for letting me know @vasilii-kovalev!

Unfortunately, there's a bug in the current version of devtools. It nests the hooks even when they're not actually nested:

![image](https://user-images.githubusercontent.com/1500684/96632810-7ed2a480-12d5-11eb-9ba5-f88c84651fc8.png)


I saw @bvaughn on twitter the other day announce that there's a new release of the DevTools coming out soon, so hopefully that fixes the nesting and I'll update the screenshots.

**Comment by bvaughn** [comment]
Which version of DevTools are you both using?

**Comment by kentcdodds** [comment]
Ah, I think it may have something to do with https://github.com/kentcdodds/stop-runaway-react-effects

If I disable that, then this issue goes away. Interestingly, I can't reproduce this in a codesandbox: https://codesandbox.io/s/little-forest-f57g4 But if I download that codesandbox and run it locally then I *do* have the issue.

So it appears that this only happens when:

1. You're using `stop-runaway-react-effects`
2. You're running locally (not in codesandbox).

I understand if this is as far as your involvement goes @bvaughn. stop-runaway-react-effects is hacky and I'm not entirely surprised that this is happening.

**Comment by bvaughn** [comment]
Yeah it doesn't look broken to me when I view the sandbox:
![Screen Shot 2020-10-20 at 5 42 49 PM](https://user-images.githubusercontent.com/29597/96647463-b48a8400-12fb-11eb-8179-4dfcf79c8f38.png)

Haven't downloaded or dug into that other hook though. I guess ping me again if you think it's a problem on my side.

**Comment by kentcdodds** [comment]
I've decided to remove stop-runaway-react-effects completely, so this should be correct now.
