### ISSUE TITLE
Could not reproduce error in Part 2 extra 3, is it due to React 17 ?

### ISSUE THREAD

**Issue by flaviuse** [kentcdodds/advanced-react-hooks#86]
Hello,
I tried to replicated the error demonstrated in part 2 (useCallback) extra 3. I could not get the expected error message when unmounting the component before the invocation of the dispatch invoked by the `run` asynchronous callback:
```
 const run = React.useCallback(promise => {
    dispatch({type: 'pending'})
    promise.then(
      data => {
        dispatch({type: 'resolved', data}) <=== Should throw the React error when component is unmounted
      },
      error => {
        dispatch({type: 'rejected', error}) <=== Should throw the React error when component is unmounted
      },
    )
  }, [])
```
The error expected by the tutorial:
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`

I tried to search in the changelog of React 17 but could not find if it was related. Is this error now prevented by React or just a weird thing in my local setup ?

**Comment by kentcdodds** [comment]
For this one you'll have to rely on the tests because I changed the way the app works in this one. So changing the exercise like I did in the video won't work anymore. Before, I just rendered the component directly in the exercise area. Now I render an iframe. So when you change the exercise, you're basically closing the tab for that page so it's no longer running at all.

I added a test to help you make sure you got it working correctly though :)
